import os
import json
import time

version_file = "version.json"
src_folder   = "src"
header_file  = src_folder + os.path.sep + "version.h"


def make_header(version):
    return f"""
/**
* DO NOT MODIFY THIS FILE!
* IT IS AUTO GENERATED BY:
*   build_version.py
*   build time:{time.ctime()}
*/
#ifndef VERSION_H
#define VERSION_H
    #define VERSION "{version}"
#endif
"""

print("Build Version:")
v = {"version": "0.0.0"}
if os.path.exists(version_file):
    with open(version_file,'r') as fd:
        v = json.load(fd)
else:
    print("\tcreating version.json")
    with open(version_file,'w') as fd:
        json.dump(v,fd)

version = v["version"].split(".")
version[2] = str(int(version[2])+1)
print(f"\tVersion major:{version[0]} minor:{version[1]} build:{version[2]}")
v["version"] = f"{version[0]}.{version[1]}.{version[2]}"
print(f"\tcreating header file:{header_file}")
with open(header_file,"w") as fd:
    fd.write(make_header(v["version"] ))
print(f"\tupdating:{version_file}")
with open(version_file,'w') as fd:
    json.dump(v,fd)